# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e06795ee74e6291243df3630aef28abe"
name = "post-purchase-app"
handle = "post-purchase-app-78"
application_url = "https://be4695c9f158.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://be4695c9f158.ngrok-free.app/auth/callback",
  "https://be4695c9f158.ngrok-free.app/auth/shopify/callback",
  "https://be4695c9f158.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
