# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e06795ee74e6291243df3630aef28abe"
name = "post-purchase-app"
handle = "post-purchase-app-78"
application_url = "https://ad9be5b6b219.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_checkouts,write_checkouts,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://ad9be5b6b219.ngrok-free.app/auth/callback",
  "https://ad9be5b6b219.ngrok-free.app/auth/shopify/callback",
  "https://ad9be5b6b219.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
